/** @type {import('tailwindcss').Config} */
module.exports = {
  presets: [require("nativewind/preset")],
  darkMode: "media",
  content: ["./src/app/**/*.{js,ts,jsx,tsx}", "./src/components/**/*.{js,ts,jsx,tsx}", "./src/features/**/*.{js,ts,jsx,tsx}"],
  safelist: [
    "caption2-fa",
    "caption1-fa",
    "body2-fa",
    "body1-fa",
    "sub-h-fa",
    "H2-fa",
    "H1-fa",
    "title-s-fa",
    "title-m-fa",
    "title-l-fa",
    "text-primary",
    "text-darkPrimary",
    "text-lightPrimary",
    "text-BrandColor",
    "text-disabledText",
    "text-brightGold",
    "text-mohajerGold",
    "text-mohajerRed",
    "text-mohajerGreen",
    "text-blackText",
    "text-spetial",
    "text-lightBlueBg",
    "text-bgColor",
    "text-darkerBgColor",
    "text-blueStrokeColor",
    "text-strokeColor",
    "text-lightStroke",
    "text-lightGold",
    "text-goldStroke",
    "text-lightRed",
    "text-hoverRedBg",
    "text-darkerRedBg",
    "text-lightGreen",
    "text-white",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#0466C8",
        BrandColor: "#004B55",
        darkPrimary: "#0252A1",
        lightPrimary: "#1379DF",
        disabledText: "#999999",
        brightGold: "#F8D41C",
        mohajerGold: "#C89D04",
        mohajerRed: "#C80404",
        mohajerGreen: "#25BD18",
        blackText: "#28262E",
        spetial: "#20C997",
        lightBlueBg: "#EFF7FF",
        bgColor: "#F9F9F9",
        darkerBgColor: "#F5F5F5",
        blueStrokeColor: "#B4CEE7",
        strokeColor: "#E9E9E9",
        lightStroke: "#F7F7F7",
        lightGold: "#FFF9E5",
        goldStroke: "#FFEEB2",
        lightRed: "#FFEFEF",
        hoverRedBg: "#FFE8E8",
        darkerRedBg: "#FAD5D5",
        lightGreen: "#DBFCDE",
        secondaryOrange: "#ED6E33",
        orange100: "#FBE2D6",
        slate500: "#64748B",
        gray50: "#F6F6F6",
      },
      borderRadius: {
        "small-radius": "5px",
        "medium-radius": "10px",
        "large-radius": "15px",
      },
      fontFamily: {
        poppins: ["Poppins-Regular"],
        "poppins-medium": ["Poppins-Medium"],
        "poppins-bold": ["Poppins-Bold"],
      },
      boxShadow: {
        "green-light": "0px 0px 80px rgba(202,255,198,1)",
        "red-light": "0px 0px 80px rgba(255,198,198,1)",
      },
    },
  },
  plugins: [],
};
